#Postgresql


server:
  port: 8082

#main:
#  banner-mode: off

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/microservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
#   Automatic creation of entity table, update table
    show-sql: true
#    check on console which queries generated on console
#


################Eureka client Configuration ###########
  application:
    name: Hotel-Service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

